name: Run Lint
on: [push]
jobs:
  run-lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup packages
        run: pip install -r requirements.txt

      - name: Run lint
        run: flake8 src/main.py
      