name: Run Test
on: [push]
jobs:
  run-test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup packages
        run: pip install -r requirements.txt

      - name: Run test
        run: pytest
      