name: Run Test
on: [push]
jobs:
  run-test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: ls -l
      - run: which python3 && python3 -V
      - run: which python && python -V
      - run: which pip && pip -V
      - run: which pip3 && pip3 -V
