name: Test Python Version
on: [push]
jobs:
  run-test-python:
    runs-on: ubuntu-latest
    steps:
      - name: print python version(ubuntu default)
        run: |
          ls -l /usr/bin | grep python
          python -V
          python3 -V
      
      - uses: actions/setup-python@v2
        with: python-version: '3.9.x'
      
      - name: print python version(use actions/setup-python@v2)
        run: |
          python -V
          python3 -V

      